### ISSUE TITLE
Add Quotes page as quote, quotes or rfq.html

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#10]
Add a RFQ or Quote/Quotes page as quote, quotes, or rfq.html

This page should be mostly like a contact page, but provide a means for the user wishing to make a quote request or request for quote (rfq) to attach and upload their documentation, i.e. .png, jpeg/jpg, gif, pdf, CAD files like .dwg, dxf, step, iges files.

The form should gather information to the database such as:

Business Name (if the person doing a RFQ is a business)
Name (if person is not a business)
Address (assuming USA includes City/Town, County, State and ZipCode/Postal Code
Phone Number
Fax Number
Website
email address
Mobile/Text Number
Contact Person at above business

Text area (maximum 1500 characters)

**Comment by Rmichal503** [comment]
I can do this page and also contact but I need more info about what you want on them

**Comment by Rmichal503** [comment]
maybe you thought about rewriting the page on React it'll be easier to move thru contact/jobs/quotes etc by implementing Routing, if you want I also can rewrite whole page to React

**Comment by gbowne1** [comment]
I am adding the details to the initial post above.

As for REACT, not at this point, that could be done as either a seperate project or as a different or a feature branch.. but right now that would b e beyond the scope of this project.

**Comment by Rmichal503** [comment]
@gbowne1  okey, you can assign me to this issue, if you want that user can send rfq we have to use something like Emailjs or write whole backend which handle email service, there is no other way. Firstly I do frontend (styling, form etc) and next we will see how do you want to do this

**Comment by gbowne1** [comment]
Ok, I have assigned you. 

This is a template site, so ideally the best solution would be so that the end user would not have to do a lot of work to get the site running.

Including unpacking the database SQL etc.

Perhaps even go as far as using the included workflows and actions to build and test the site.
