### ISSUE TITLE
Dark Mode contrast between nav bar and body

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#102]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/gbowne1/spmssite/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/gbowne1/spmssite/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/gbowne1/spmssite/issues) that already report this problem, without success.

### Current Behavior

There is not enough contrast between the navbar and body when in Dark Mode.  You can barely tell where the bottom of the nav bar is 

### Expected Behavior

More contrast.  

### Steps to Reproduce

Try it.

**Comment by Pathholder1806** [comment]
Hey @gbowne1 !
I would like to look into the issue!

**Comment by Pathholder1806** [comment]
@gbowne1 !
I looked up into the issue and I would like to contribute to it!

So looking into the issue there are 2 possible solutions for adding the contrast:
- Make the navbar more darker than the body.
- Make the navbar slightly lighter than the body.
Which one would you prefer so that we can move ahead

This is when we move navbar background one shade **lighter** than the body
![image](https://user-images.githubusercontent.com/61896647/190324039-451428cf-5ab0-4c51-b4d9-48f3e8728e73.png)

This is when we move to the **darker** shade
![image](https://user-images.githubusercontent.com/61896647/190324435-dc7463f6-57d0-4600-b57c-da4ecfe5f5db.png)

**Comment by gbowne1** [comment]
Sure, 

I would prefer the darker shade, but that may need some A vs B testing for some end users.

**Comment by Pathholder1806** [comment]
Hey @gbowne1 !
So let me generate the Pr with my proposed darker shade and then we can make further updates.

**Comment by gbowne1** [comment]
I would wait till the next merge is complete.. unless there would be no merge conflicts.

**Comment by Pathholder1806** [comment]
Hey @gbowne1 !
My branch went into a merge conflict. Are there any other changes coming from another merge ?

**Comment by gbowne1** [comment]
Yes.
I added the major changes I did today after some testing which just finished.
Go back and sync.

**Comment by gbowne1** [comment]
I sent you an invite too/

If you didn't get it let me know.

**Comment by Pathholder1806** [comment]
Yes I received the invitation. Thank you!
I synced my branch now shall I create a PR again ?

**Comment by gbowne1** [comment]
Yeah, Please do.  I also sent an invite to my org.  there are projects there to work on if you like.

**Comment by Pathholder1806** [comment]
Hey @gbowne1 !
Generated the PR. Kindly review my proposed changes and suggest any further updates if any!

**Comment by gbowne1** [comment]
Review done and merged.  Looks good.  

If you didn't get it.. go here: https://github.com/orgs/taotnpwaft/teams and request to be on a team including member.

Thanks for the PR!

**Comment by gbowne1** [comment]
Quite a bit of testing still needs done with this particular project.

**Comment by Pathholder1806** [comment]
Always up for lending a helping hand🤝🏻

**Comment by gbowne1** [comment]
There's plenty to do.  I have a new issue with the about page.. notice how the content scrolls above the jumbotron/hero and navbar.

**Comment by gbowne1** [comment]
Don't see a project you'd like to do in the org.  I will take suggestions that will improve the community.
