### ISSUE TITLE
Clean up the CSS or move to SCSS

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#104]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/gbowne1/spmssite/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/gbowne1/spmssite/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/gbowne1/spmssite/issues) that already report this problem, without success.

### Current Behavior

Looking through the current styles.css file it is very heavy and not very well organized.

Sort the CSS by using commented section headers in the CSS  using /* */ i.e; 

```css
/* Body */

body {
  background: #blue;
},

/* Header */

header {
  color: #blue;
}
```

Thinking about this, Bootstrap 5.2 CDN sends out SCSS files so it might be handy to just convert the css to SCSS instead.

This is a more advanced task but not impossible.

 

### Expected Behavior

Better CSS

### Steps to Reproduce

Try it.

**Comment by gbowne1** [comment]
Please see: #110

**Comment by gbowne1** [comment]
I was thinking the other day that a number of lines in this styles.css file were meant for individual pages.

That stuff could be moved to individual files for each component and maybe even try adding a index.css for global styles  like a node/express/react app would have.

A side note here:
I am sure one could write a index.js or app.js to run some of the sites functions in jQuery or JS.

**Comment by Rikarox** [comment]
Hello, I understand what you want to achive and I would like to work on this issue, can you assigne me?

**Comment by gbowne1** [comment]
Oo @Rikarox Thanks.

**Comment by gbowne1** [comment]
The changes look good.

I am approving merge.
