### ISSUE TITLE
About page current issues

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#108]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/gbowne1/spmssite/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/gbowne1/spmssite/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/gbowne1/spmssite/issues) that already report this problem, without success.

### Current Behavior

Content of About page currently scrolls above the header and navbar.

### Expected Behavior

I would expect the content to be static while scrolling.

### Steps to Reproduce

Scroll the about.html page up and down

**Comment by NageshMandal** [comment]
I want to work on this issue. Could you please assign it to me.

**Comment by gbowne1** [comment]
Ok.

**Comment by gbowne1** [comment]
Closed with fixed by recent merge.
