### ISSUE TITLE
Employee Login modal does not work.

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#109]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/gbowne1/spmssite/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/gbowne1/spmssite/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/gbowne1/spmssite/issues) that already report this problem, without success.

### Current Behavior

Yay! I added a Employee Login button which should bring up a modal 

I added some stubs for this in the code.  But it needs finished.

Need some help with this? there's a good freecodecamp

https://www.freecodecamp.org/news/how-to-create-a-login-feature-with-bootstrap-modal-and-jquery-ajax-53dc0d281609/

Or you can do something like this but it would need some work.

https://codepen.io/maheshd/pen/xVvdaw

### Expected Behavior

Working Employee Login 

### Steps to Reproduce

Try it in your browser with a Live Server extension or Preview extension, or download and open in the browser.

**Comment by devAdrish** [comment]
I can help

**Comment by devAdrish** [comment]
can u assign this to me.

**Comment by gbowne1** [comment]
Ok @devAdrish
