### ISSUE TITLE
Add Contact page as contact.html

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#11]
Add a Contact page with:

- Bootstap 
- FontAwesome

Fields:

Business Name {name of the business
Address: {assuming USA} Street address, City/Town, County, State, Zip Code/Post Code w/4 digit allowed} and country
Contact Name: {Business contact name}  
Name: {if person requesting a quote is an individual not associated with a business
Website: {website of business or individual}
Email: {email address of business or individual}
Text area allowing max 1,500 characters.  
Add a google map / pin if that is helpful.

Fonts:

Google Roboto, OpenSans, Monsterrat, Lato, Minimum 19.2px, Normal.

**Comment by developer-irfan** [comment]
Hello @gbowne1 i want to contribute on this, i will create contact page with given fields or fonts with given validations.

**Comment by gbowne1** [comment]
Sure, if you would like to work on this I can assign you to it. @developer-irfan
