### ISSUE TITLE
index.html's dropdowns are not working but on other pages they work

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#111]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/gbowne1/spmssite/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/gbowne1/spmssite/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/gbowne1/spmssite/issues) that already report this problem, without success.

### Current Behavior

index.html's dropdowns are not working but on other pages they work

### Expected Behavior

Working dropdowns

### Steps to Reproduce

Try it.

**Comment by SergeyKharkovshchenko** [comment]
Hey, I think I can take care of this issue. Could you please assign it to me?

**Comment by gbowne1** [comment]
Ok @SergeyKharkovshchenko

**Comment by gbowne1** [comment]
Ok @SergeyKharkovshchenko

**Comment by SoyebSarkar** [comment]
hey, @gbowne1 I want to contribute, I think I can fix this

**Comment by gbowne1** [comment]
Ok @SoyebSarkar

**Comment by SoyebSarkar** [comment]
<img width="375" alt="image" src="https://user-images.githubusercontent.com/96381266/191068690-d98c1e7b-94a1-47a9-80f3-012153c3bccb.png">

@gbowne1 now it's working, please review it and let me know if it is ok

**Comment by gbowne1** [comment]
Seems to work fine now.
