### ISSUE TITLE
Employee Login Button & Modal

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#114]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/gbowne1/spmssite/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/gbowne1/spmssite/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/gbowne1/spmssite/issues) that already report this problem, without success.

### Current Behavior

The added Employee Login button now works with a modal.

- Needs border radius on right side of fields.
- Needs some form of validation, with error messages using one of the usual PHP, JavaScript, Ajax, jQuery etc.  
- This needs labeled fields.
- Show logged in and logged out status
- More styling of the modal.

Maybe a few other things but that should get started.

### Expected Behavior

Now that modal actually works make it useful as employee login.

### Steps to Reproduce

Try it.

**Comment by knownasaritra** [comment]
can I work on this ?

**Comment by gbowne1** [comment]
Sure @knownasaritra

**Comment by knownasaritra** [comment]
@gbowne1 current WIP, I am doing the validations based on a test  array inside the validation script, is it fine ?

**Comment by gbowne1** [comment]
@knownasaritra 

Yes, that is fine.

**Comment by Janvcd** [comment]
Can I work on this for you??

**Comment by gbowne1** [comment]
Sure

**Comment by knownasaritra** [comment]
@gbowne1 I did these:

- Needs border radius on right side of fields.
- Needs some form of validation, with error messages using one of the usual PHP, JavaScript, Ajax, jQuery etc.
- This needs labeled fields.
- Some styling of modal
- ~~Show logged in and logged out status~~ , not getting logged out status, can you please explain it ?

**Comment by gbowne1** [comment]
@knownasaritra thats great.  Thanks.
 
There should be some way of show that the user has been logged out.

Here is a stackoverflow post that might help.
https://stackoverflow.com/questions/10051586/how-to-log-out-showing-the-proper-status

**Comment by gbowne1** [comment]
Anyone working on this, The modal also needs a cancel button.

**Comment by knownasaritra** [comment]
I have added code for the cross button for the modal , I will add the cancel button as well

**Comment by gbowne1** [comment]
Great thanks @knownasaritra

**Comment by gbowne1** [comment]
@knownasaritra @Janvcd  do you have a PR ready?

**Comment by knownasaritra** [comment]
@gbowne1 I will provide by today , got busy , really sorry

**Comment by Janvcd** [comment]
@gbowne1 On it. Was busy in some work.

**Comment by gbowne1** [comment]
Ok.  Thanks.

**Comment by knownasaritra** [comment]
@gbowne1 my pull request is drafted , please have a look , due to time constraint I could not work on the style and positioning of the **logout button**  and the **logged in status**, please have a look and let me know.

**Comment by gbowne1** [comment]
Merged.  Thanks for the PR.  @ak090498

**Comment by gbowne1** [comment]
Anyone that wants to finish the work in the employee login form can do so.

**Comment by ak090498** [comment]
@gbowne1 thanks for merging it's my first PR glad I could make it

**Comment by gbowne1** [comment]
@ak090498 you're welcome.  I see you joined the Discord too.  Feel free to contribute to our projects

https://github.com/taotnpwaft/
