### ISSUE TITLE
Image link is broken in index.html

### ISSUE THREAD

**Issue by SoyebSarkar** [gbowne1/spmssite#116]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/gbowne1/spmssite/blob/main/.github/CONTRIBUTING.md).
- [x] I agree to follow the [Code of Conduct](https://github.com/gbowne1/spmssite/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/gbowne1/spmssite/issues) that already report this problem, without success.

### Current Behavior

The image link is broken. There is no logo.jpg file in \spmssite\src\images
<img width="667" alt="image" src="https://user-images.githubusercontent.com/96381266/190849501-acbd9915-aefe-4969-bde4-31e26d39b60d.png">

### Expected Behavior

There should be a logo.jpg file 

### Steps to Reproduce

Add the logo.jpg
link the 'logo.jpg'  path in the image tag in the index.html

**Comment by SoyebSarkar** [comment]
@gbowne1 I want to fix this problem

**Comment by gbowne1** [comment]
Its a placeholder for an image.

You can use logoipsum.com and pick a suitable logo to use.

Either way, make sure all of the headers get logos.

**Comment by SoyebSarkar** [comment]
ok please assigned me this I need permission for pr
<img width="594" alt="image" src="https://user-images.githubusercontent.com/96381266/190871083-e0647229-c966-44ef-a1ce-72d470fc3ed9.png">

**Comment by SoyebSarkar** [comment]
I have created a pr #120 @gbowne1 please review and let me know if it is ok

**Comment by SoyebSarkar** [comment]
> Its a placeholder for an image.
> 
> You can use logoipsum.com and pick a suitable logo to use.
> 
> Either way, make sure all of the headers get logos.

<img width="720" alt="image" src="https://user-images.githubusercontent.com/96381266/190872078-3413150d-1de9-408a-9734-88753e59ae92.png">
I have created a pr #120 @gbowne1 please review and let me know

**Comment by gbowne1** [comment]
I would certainly use a logo, but not one with Logoipsum branding.

**Comment by SoyebSarkar** [comment]
> I would certainly use a logo, but not one with Logoipsum branding.

thank you for your review 
<img width="744" alt="image" src="https://user-images.githubusercontent.com/96381266/190876297-7d932529-15c7-46ad-8337-ac74111dec02.png">

<img width="616" alt="image" src="https://user-images.githubusercontent.com/96381266/190876314-334bb69e-faaa-413b-ab81-e584b53c828d.png">
I changed the logo, please check and let me know
