### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#3]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/gbowne1/spmssite/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/gbowne1/spmssite/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/gbowne1/spmssite/issues) that already report this problem, without success.

### Current Behavior

Way too many tabs in the Navbar

### Expected Behavior

Only 3-5 Navigation menu items at the top level.

Categorize the ~15 items into 5 categories.  Move the rest into dropdowns.

### Steps to Reproduce

Load the index.html page from / or index.html

**Comment by prakhartiwari2507** [comment]
I could help you with that. May I?

**Comment by prakhartiwari2507** [comment]
Can you name the categories and what tabs you want to be inside them? I will help in the creation.

**Comment by gbowne1** [comment]
That would be great @prakhartiwari2507 ..  

Here is a screen shot from a recent render..

![Screenshot 2022-08-13 at 21-36-29 Seattle Precision Machine Shop](https://user-images.githubusercontent.com/47549872/184730038-3e1496ac-a17b-4aed-b26e-b95e1d33f610.png)

I was thinking that "About" and "History" could be one menu

The next menu would have "Materials", "Capabilites", "Services", "Equipment" and Gallery.

Contact, Careers, Blog and Testimonials could go in the next menu.

Blog, Quality and Quotes am not sure about but they could be sperate if not part of the footer.

**Comment by prakhartiwari2507** [comment]
Hey, I was exploring the code and found it too messy, can you try to clean up it a little bit? The divs, navs, and many other things are very nested and are making it difficult to understand what to change.

**Comment by gbowne1** [comment]
It is a bit nested.  A lot of it has to do with Bootstrap.  I'll look into it.  Is there any particular reason it is hard though?

**Comment by prakhartiwari2507** [comment]
Oh, Bootstrap, I actually work from scratch projects, I know a little bit of bootstrap, but not much. If you would like to make the website from scratch then I can help with that, but if Bootstrap is used, I will not be helpful for you sadly.

**Comment by gbowne1** [comment]
Oh ok, yeah Bootstrap requires a lot of different stuff with div's. This isn't a fully from scratch project as I already have offered the beginngs of a index.html and the css.

**Comment by Vansh-Baghel** [comment]
OK so u want to reduce and give styling to the navbar
And it must be _dropdown_ with reduced categories
**Anthing else?**

**Comment by Vansh-Baghel** [comment]
Do you want me to remove bootstrap and make it using pure css and html?

**Comment by Rmichal503** [comment]
I also think that Bootstrap here is unnecessary, for such small site better solution will be pure css
