### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#30]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/gbowne1/spmssite/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/gbowne1/spmssite/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/gbowne1/spmssite/issues) that already report this problem, without success.

### Current Behavior

Current Render of Footer

![Screenshot 2022-08-17 at 16-03-11 Seattle Precision Machine Shop](https://user-images.githubusercontent.com/47549872/185258667-51668d64-cdfa-44cb-8d45-4f77e222b8a3.png)
.

### Expected Behavior

Something like this example from MDBootstrap:

![footerexample](https://user-images.githubusercontent.com/47549872/185258705-8f09188b-8d44-4e03-940d-e2718dd8e27a.jpg)

Perhaps add Google Maps w/Pin {a random location that end user can edit}

### Steps to Reproduce

Load current render

**Comment by Darrkzero** [comment]
I will like to help do you have the necessary information to fill those part

**Comment by gbowne1** [comment]
Yeah, I do. 

This is a website tempate so contact details can be random left for the end user to fill in.

**Comment by gbowne1** [comment]
It would be also great if the Footer was a reuseable component appearing in most of the pages.

**Comment by pranavmadhu01** [comment]
> It would be also great if the Footer was a reuseable component appearing in most of the pages.

then it would be better if we do the website in reactjs

**Comment by gbowne1** [comment]
PHP would do it too.  just add a /components folder/directory and use a PHP include linked to each component.

Related:
https://www.php.net/manual/en/function.include.php

You would have something like header.php or footer.php in the /components folder/dir and just link it.  Thats how the TAOT site works right now.

I don't know if JS, jQuery or Ajax would statically do that.  May require building out the index.js or a seperate server.js the index file would pick up and help route things and components.  Not hard to make a http server.

I thought about adding serviceWorker.js, a manifest.json and some stuff the browser(s) would pick up

**Comment by gbowne1** [comment]
At some point we could releast the template as a React project, .NET/IIS and a Wordpress template... that would increase useablitliy across multiple genres.  Not every business wants or uses the same technologies.
