### ISSUE TITLE
Add Footer to index.html

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#4]
index.html does not have a footer.

Add a footer that includes:

- Shop Business Name
- Address (assuming USA)
- Phone
- Fax
- email address contact
- FontAwesome Social Icons
- Business hours (assuming Monday - Friday)
- Copyright info with Business Name, Host or Developer {with link}

Google Maps // Pin?

**Comment by gbowne1** [comment]
Also a Terms and Conditions and Privacy Policy (link to a PDF file??)

**Comment by SifonSolomon** [comment]
I would love to work on this project.

**Comment by gbowne1** [comment]
Okay. I have added you.

**Comment by SifonSolomon** [comment]
ok
