### ISSUE TITLE
feat: Icons and logo placeholder image

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#42]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/gbowne1/spmssite/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct]().
- [X] I have searched for [existing issues]() that already include this feature request, without success.

### Describe the Feature Request

There is no favicon and no place for end user to place their logo.

### Describe the Use Case

Requirements for good sites include a good favicon and a image placeholder.  Especially for SEO.

### Describe Preferred Solution

Requirements for good sites include a good favicon and a image placeholder. Especially for SEO.

**Comment by jlmb54** [comment]
Hi, i started working on this issue as well and already did a merge request.
