### ISSUE TITLE
Add FontAwesome Social Icons

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#5]
This template site does not have any FontAwesome Social Icons either on footer or header 

Either placement would be ok.

Add placeholder icons for Instagram, Facebook, LinkedIn, Yelp, Twitter, etc. so that the user can use it to add their appropriate links.

**Comment by prakhartiwari2507** [comment]
Sure, I will be doing so.

**Comment by Dikshatomarr** [comment]
I'm willing to work on this issue.

**Comment by gbowne1** [comment]
Thank you.  You can work on the issue.

**Comment by gbowne1** [comment]
I have assigned both of you

**Comment by gbowne1** [comment]
This issue was resolved today but here is the current render.

**Comment by gbowne1** [comment]
In Firefox v103 I can only see the top 3/4 of the page and it does not scroll.

**Comment by VincentWoglo** [comment]
When I forked the repository, same happened on my end.

**Comment by gbowne1** [comment]
Should be fixed as of now.

Make sure youre up to date.  I merged changes that should take care of that issue.

Let me know.  I wont be back for 3-4 more hours to test.

**Comment by gbowne1** [comment]
It works, I tested it.  Might be a slight problem with your local.
