### ISSUE TITLE
Styling for jobs.html

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#55]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/gbowne1/spmssite/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/gbowne1/spmssite/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/gbowne1/spmssite/issues) that already report this problem, without success.

### Current Behavior

This needs quite a bit of styling work.

A lot of the fields are too large and a few are not the right type. Some are too close together.

It is also not ready to connect to the backend.

### Expected Behavior

A nicely styled form easily able to be connected to the backend // database.

Using..

  PHP,  jQuery, Ajax, JavaScript...

Also test whatever scripts exist.. and write missing code.

 This should also send both an email or some notificatio  to both HR department and the user filling out the form that 

 Also most of the form needs validation script to make sure of no empty fields, incorrect information, etc.

### Steps to Reproduce

Load the index.html and click on the Careers button in the menu.

Use a preview or Live Server extension to view the page.

**Comment by MirandaBrawnerSavannah** [comment]
I can start working on this. I'm new to this project, never contributed before, but I'll give it a try.

**Comment by gbowne1** [comment]
Alright. Thanks :-)

**Comment by MirandaBrawnerSavannah** [comment]
I have some feedback about the content of the jobs form.

Do you think that the Date field at the top is necessary? It might make sense on a form that's printed out, but for an online form, we could use the system date from when they filled out the form.

I also think we should leave out the questions asking about someone's criminal record. Excluding people based on past legal trouble is not a good idea, because it leaves people in a trap where they can't find a job, and have no way to make a living except possibly by illegal means, which forces them back into the prison system even when they are trying to earn an honest living. Also, the criminal justice system isn't exactly fair. It's often very discriminatory, and each step of the process multiplies the discriminatory effects, from policing to bail to sentencing, etc. We don't want for employers to duplicate the unfair effects of the criminal justice system.

There are also state and federal laws that prohibit asking questions like this, and while there are some exceptions to those laws, I think it makes sense for our templates to leave them off, for the reasons above.

**Comment by gbowne1** [comment]
It's a very old form that resided on my original website.  So, yes, it needs a lot of work to be made current and legal.

The original form did allow us to print after it got sent to the ERP/MRP system and HR.

**Comment by MirandaBrawnerSavannah** [comment]
Ok. What would you like me to do about the date, then? Leave the field and auto-fill it with the current date?

**Comment by gbowne1** [comment]
I don't know if it's really necessary to have the Date field.  But if it's left in the form, I am all for using

`<input type="date">` or `<input type="datetime-local">` but it should autofill.

If we add jQuery UI from their CDN there is a nice datepicker from:

<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

[Datepicker - jQuery UI](https://jqueryui.com/datepicker/)

**Comment by gbowne1** [comment]
I also forgot to add Google Recaptcha

https://developers.google.com/recaptcha/docs/v3

**Comment by MirandaBrawnerSavannah** [comment]
Ok, thanks.

**Comment by gbowne1** [comment]
The original also included a blue background that was somewhere between light and medium blue but some may want a more pleasing background.. and make them into separate cards or panels in the UI, rather than `<br>` and `<hr>.`

**Comment by gbowne1** [comment]
I might even suggest to put in stub links to external sites like monster.com or indeed so that the end user can link to their job listing sites/apps.

**Comment by MirandaBrawnerSavannah** [comment]
Would you like me to replace all references to Seattle Precision Machine Shop in the text?

**Comment by gbowne1** [comment]
Yes, please remove all reference to my old business name.  Haven't named the actual template yet so just left it where it was when I stopped using it.  Thanks @MirandaBrawnerSavannah

**Comment by MirandaBrawnerSavannah** [comment]
Sounds good. Another question: When you say it should be able to connect to the back end and send an email, do you have a back end set up yet? If not, can that be a separate pull request?

**Comment by MirandaBrawnerSavannah** [comment]
Also, I'm not sure I understand why this list of links is divided into 2 parts. Is there a difference between the first set of links and the second set?

<img width="254" alt="Seattle Shop Links" src="https://user-images.githubusercontent.com/56093884/186518025-26fce938-123e-44dd-bae2-6bcec96d5223.png">

**Comment by gbowne1** [comment]
I am no longer using this site.  but the database // backend work could/would be made easier if we ship a basic database // sql someone would have a easier time integrating.  

As for the links those can be removed.. remnants of the old site.

**Comment by MirandaBrawnerSavannah** [comment]
I posted a pull request with the work I've done so far.
https://github.com/gbowne1/spmssite/pull/70

**Comment by gbowne1** [comment]
Alright.  I will have a look. Its marked as a draft PR which arent able to be merged.


Thanks for the PR!
