### ISSUE TITLE
Missing FontAwesome Icons 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#63]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/gbowne1/spmssite/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/gbowne1/spmssite/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/gbowne1/spmssite/issues) that already report this problem, without success.

### Current Behavior

The stripe at the top of footer is missing FontAwesome icons for:

- Instagram
- YouTube

### Expected Behavior

Includes Instagram and YouTube.

Might also want to add an iframe for at least one YouTube video (use the YouTube API?) to the About page so that end user may add a video link to their YouTube.

### Steps to Reproduce

Try it!  

Use a Live Server or Preview extension in VSCode.. etc.

**Comment by developer-irfan** [comment]
@gbowne1 assign me this so i can add font awesome icons.

**Comment by gbowne1** [comment]
Alright.  Thanks! :-)

**Comment by wyenelle** [comment]
are there any other issues with this project i cant hook into?

**Comment by gbowne1** [comment]
@wyenelle I am going to add a number of issues soon. but there are plenty already.
