### ISSUE TITLE
Libraries

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#74]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/gbowne1/spmssite/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/gbowne1/spmssite/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/gbowne1/spmssite/issues) that already report this problem, without success.

### Current Behavior

There are currently two versions of jQuery library CDN's in the `<head>` tag:

`<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>`

and 

`<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>`

The current version is 3.6.  The 3.2.1 needs to be removed from the head tag  Having duplicate CDN's usually will cause the browser to get confused.

### Expected Behavior

No duplicate CDN's.

### Steps to Reproduce

Try it and open the browser console.

**Comment by gbowne1** [comment]
This the bootstrap 5.2 JavaScript CDN is also missing from the head

`<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.0/js/bootstrap.min.js" integrity="sha512-8Y8eGK92dzouwpROIppwr+0kPauu0qqtnzZZNEF8Pat5tuRNJxJXCkbQfJ0HlUG3y1HB3z18CSKmUo7i2zcPpg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>`

**Comment by mehakg867** [comment]
Can I work on it..?

**Comment by gbowne1** [comment]
Sure. I will assign you.

**Comment by gbowne1** [comment]
Libraries were fixed today Aug 29, 2022 to include updated and missing CDN's for Bootstrap, FontAwesome and PopperJs.
