### ISSUE TITLE
Google Maps Issues

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#78]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/gbowne1/spmssite/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/gbowne1/spmssite/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/gbowne1/spmssite/issues) that already report this problem, without success.

### Current Behavior

This is a reference to another issue # 

Google Maps servers and its API are sending out several Content-Security-Policy issues.I 

### Expected Behavior

No CSP issues,

### Steps to Reproduce

Use preview or live server extension in your editor or IDE and look at the browser console.

**Comment by ketsebaotgizachew** [comment]
didn't see any errors given by google maps does it still exist or has it been fixed

**Comment by gbowne1** [comment]
Well @ketsebaotgizachew looks like if we are to acheive little to no errors in browsers we will have to do lots of useability and different browser testing.

Firefox can be a pain.

I will do another round of Google Lighthouse tests today in Google Chrome.

There is also no breakpoints for laptop views.  Someone might be looking at the site on iPad and Laptops.  I would also test in Windows 10 native browser Edge/Chromium

**Comment by ketsebaotgizachew** [comment]
after a couple of investigation that i have been doing the Content Security Policy: Ignoring “'report-sample'” within script-src: ‘strict-dynamic’ specified  and other errors are happening b/c google maps server conflicts with firfox csp but nothing more . wont cause problems so it is safe to ignore

**Comment by gbowne1** [comment]
Yes, it's a known issue.  Not a priority issue to deal with at the moment.
