### ISSUE TITLE
Add Jobs / Careers page as careers.html or jobs.html

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#8]
s for the Job / Employment Application / Careers page it should be something like this:

https://codesandbox.io/s/job-application-form-6648hu

but also list available positions.. so it should not only serve as a place for people to:
- Fill in their contact details including 
   Website URL, GitHub Link, email address(es), home/office/mobile phone, etc.
- List 3 references and their contact information
-  Upload their CV && Resume
-  IT and Dev, etc. roles link their Github 
-  Company could list their open positions, when it's filled it should stop accepting applications for that position.. or some warning toast/modal/popper saying it's been filled.
-  Schedule Interviews  {provide a calendar with day, date, time.. etc} at least semi-interactively.. it would possibly also send an email to both HR and user / person sending the application.
-  Include a printable and Fillable PDF so the person could bring in a paper job/ application or submit in real time filled.

**Comment by Rmichal503** [comment]
@gbowne1 give more info about what you want on this page, some overall vision and you can assign me

**Comment by gbowne1** [comment]
I am almost finished my work and on my way back.

I've added you to the taotnpwaft website team. Plenty to do there. See the TODO and Website.md and the issues tab. index.html and index.php are the same file but the php one loads the components so they are reuseable.

I will give some description for jobs/careers in the next hour or so.

**Comment by Rmichal503** [comment]
I saw that Im in this team and bit earlier I forked repository with website, what can I say.. its messy. There's lot of work and with PHP, SQL or JQuery I cannot help. I need little bit of time to really familiar with the code but unfortunately only
after the weekend

**Comment by gbowne1** [comment]
Yes, there's a lot to do there but feel free to contribute where you are able to.  It is a mess, but can only get better through contributions and ideas.

No worries at all.  Take your time to get to know the project and if you need any help or have some ideas ideas I can provide some details.  

PHP is only there mainly while I am setting up the actual server hardware, domain and hosting.  Which should happen soon.  Have been having some logistical problems with some of that.

**Comment by gbowne1** [comment]
Updated the requirements for this.

**Comment by gbowne1** [comment]
Added a boilerplate jobs.html today via #54 

Needs more styling, etc

**Comment by Rmichal503** [comment]
Okey but I'll do this from start, this boilerplate has over 1k lines of code and I don't really want do style this

**Comment by gbowne1** [comment]
This is from the original site with minor redactions/changes.

Can you use much of it to create the new one?

Have a look at it first.
