### ISSUE TITLE
Add a Privacy policy and terms and conditions 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#84]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/gbowne1/spmssite/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/gbowne1/spmssite/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/gbowne1/spmssite/issues) that already report this problem, without success.

### Current Behavior

There is no privacy policy and terms and conditions link to   either a page or a link to a download to a pdf file(S)

Privacy policy could just be a modal/popup.

### Expected Behavior

Most industrial genre business websites have a privacy policy and conditions.

### Steps to Reproduce

Try it.

**Comment by ighmaZ** [comment]
hi , i wanna contribute to this issue

**Comment by gbowne1** [comment]
Sure.  @ighmaZ

**Comment by gbowne1** [comment]
Added with recent merge.
