### ISSUE TITLE
feat: Filetype exclusion in file upload 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#87]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/gbowne1/spmssite/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct]().
- [X] I have searched for [existing issues]() that already include this feature request, without success.

### Describe the Feature Request

Here's the concept..

Under the "accept" of a file input, there can also be a definition of the general type of the files for selection. For example, if you put "image/*" under the "accept" attribute, the limitation will cover all the standard file formats (gif, jpeg and so on) for images and not just the type(s) by extensions. In addition, you can combine the pre-defined type(s) and extensions. For example: "image/*,.swf". For this example, the limitation will include all standard image files AND all ".swf" files. NOTE: the user can always select "All Files" from the type list in the dialog box... 

Before the file is uploaded, you can check the file's extension using Javascript, and prevent the form being submitted if it doesn't match. The name of the file to be uploaded is stored in the "value" field of the form element.

Here's a simple example that only allows files that end in ".gif" to be uploaded:

```js
    function checkFile() {
        var fileElement = document.getElementById("uploadFile");
        var fileExtension = "";
        if (fileElement.value.lastIndexOf(".") > 0) {
            fileExtension = fileElement.value.substring(fileElement.value.lastIndexOf(".") + 1, fileElement.value.length);
        }
        if (fileExtension.toLowerCase() == "gif") {
            return true;
        }
        else {
            alert("You must select a GIF file for upload");
            return false;
        }
    }
```

<form action="upload.aspx" enctype="multipart/form-data" onsubmit="return checkFile();">
    <input name="uploadFile" id="uploadFile" type="file" />

    <input type="submit" />
</form>

### Describe the Use Case

Ability to only be able to upload common files used in manufacturing and engineering context  like:

.txt
.jpg/jpeg
.png
.webp
.docx
.doc
.dwg
.dxf
.iges
.step

### Describe Alternatives

Possibly use a filetype upload select in the UI.

**Comment by BrianAndrewOneil** [comment]
Hello, I'd be happy to help you with this issue. Could you assign it to me? Thank you.

**Comment by BrianAndrewOneil** [comment]
@gbowne1 sorry to bother you, I just realized that I didn't @ you and I'm not sure if that's required for you to see this.

**Comment by gbowne1** [comment]
no it's not @BrianAndrewOneil but yes you can help.

**Comment by gbowne1** [comment]
This was meant for this file:

https://github.com/gbowne1/spmssite/blob/main/templates/rfq.html

**Comment by BrianAndrewOneil** [comment]
Okay, thank you, this makes sense. I'll work on this today.

**Comment by gbowne1** [comment]
Ok. Great. Thanks! :-) @BrianAndrewOneil

**Comment by gbowne1** [comment]
Great @BrianAndrewOneil 

thanks for submitting a PR.  I will test it and if it see if it works fine.
