### ISSUE TITLE
feat: add 404 page

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#88]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/gbowne1/spmssite/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct]().
- [X] I have searched for [existing issues]() that already include this feature request, without success.

### Describe the Feature Request

Make a pretty or pretty good 404 page when a page is not available or not found.

### Describe the Use Case

Good page flow.

**Comment by VincentWoglo** [comment]
Can you assign this one to me

**Comment by gbowne1** [comment]
Ok. There's an example in here: https://github.com/taotnpwaft/website

**Comment by gbowne1** [comment]
Here's an example..
![Screenshot 2022-09-16 at 20-16-21 404](https://user-images.githubusercontent.com/47549872/190838952-47d69bb8-3414-4e5d-81b6-b3088b17d8a7.png)

and the color is #007aff

**Comment by Janvcd** [comment]
Can you assign this to me??

**Comment by gbowne1** [comment]
Sure @Janvcd

**Comment by mominry** [comment]
Can you please assign this issue to me

**Comment by gbowne1** [comment]
Ok @mominry

**Comment by gbowne1** [comment]
PR #126 closes this.
