### ISSUE TITLE
Add a About page as about.html

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#9]
This template currently does not have a about.html page which would include a 150 word or less descripton of:

- Business History
- Call to action to go to Capabilities. etc. page(s) in the Nav.
- Bootstrap cards to show off core team members // staff {minimum of 3 cards}

**Comment by joleschmidt** [comment]
Hey @gbowne1, I would like to work on the page. Could you assign me to the issue?

**Comment by gbowne1** [comment]
Ok. Added you.

**Comment by gbowne1** [comment]
As for an about page I would suggest something like this.. with some blank cards to add the items in the OP ^^..

[Our Team](https://www.w3schools.com/howto/howto_css_team.asp)

**Comment by joleschmidt** [comment]
@gbowne1 looks good! do you want me to install bootstrap globally or should i embed it via link in the about page html?

**Comment by joleschmidt** [comment]
@gbowne1 I have finished the about page so far and oriented myself to the existing pages. Currently, there are 3 team member cards, but I could add some more if needed. I would create a pull request for the page, so you can have a look at it. If you have some more suggestions, please let me know.

**Comment by joleschmidt** [comment]
sorry.. i unassigned me accidentally. could you please assign me again?

**Comment by gbowne1** [comment]
Any dependencies should first be CDNs.. we can download and install them when we are close to 1.0

**Comment by gbowne1** [comment]
I am back.. Tested this.  Looks good!  Just needs some overall polishing.
