### ISSUE TITLE
Broken Dark Mode/Light Mode Switch

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/spmssite#99]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/gbowne1/spmssite/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/gbowne1/spmssite/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/gbowne1/spmssite/issues) that already report this problem, without success.

### Current Behavior

Clicking on the switch (hard to find/see) in light mode, does a really wierd 45deg'ish slide.

![Screenshot 2022-09-12 at 19-07-20 Seattle Precision Machine Shop](https://user-images.githubusercontent.com/47549872/189791576-32b3c4fb-94c1-4e60-b1fc-1e92b9054be9.png)

The switch and the label also are not in close proximity and also is interfering with the search bar field.

### Expected Behavior

Working

### Steps to Reproduce

Try it

**Comment by ramyashreeshetty** [comment]
Hey, we can do two things one is to change it into a button and placing beside the search bar OR we can move it into the top position.

![image](https://user-images.githubusercontent.com/43513353/189925706-1b0d4b22-18df-4d35-a915-770770a353a9.png)

**Comment by ramyashreeshetty** [comment]
let me know if this looks appropriate.
![image](https://user-images.githubusercontent.com/43513353/189938747-62f6471b-1909-4304-baf1-91bc26b6e24b.png)

**Comment by gbowne1** [comment]
Yeah thats a lot better

**Comment by ramyashreeshetty** [comment]
I sent a PR. its for the test branch do check it.

**Comment by gbowne1** [comment]
Ok I will test it out.  

It will be 3-4 hours from now till I am able to test. 

Thanks for the PR.

If you would like other things to work on I have other issues here:

https://github.com/gbowne1/personalsite

https://github.com/taotnpwaft/website

**Comment by ramyashreeshetty** [comment]
Okay thanks

**Comment by gbowne1** [comment]
The bottom one needs a lot of work still.

**Comment by ramyashreeshetty** [comment]
https://github.com/taotnpwaft/website <- u mean this one?

**Comment by gbowne1** [comment]
Yes.  I haven't had time to work on it.

The header.php needs to be finished

You can write it in html inside the php file and I'll finish it.

The index.html shows what the header and navbar looks like.

**Comment by gbowne1** [comment]
Tested and merged back to main. @ramyashreeshetty
